name: flyssh
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dio: ^5.7.0
  error_or: ^0.4.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  gap: ^3.0.1
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  openapi:
    path: ../openapi
  riverpod_annotation: ^2.3.5
  toastification: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
